/**
 * Real pain cards, baked from the Henway generator.
 *
 * NOT hand-written marketing copy. Generated by POSTing the pain-stage prompt in
 * henway backend/app/discovery.py through the app's configured model, then parsed
 * with the app's own helpers. This is what a visitor actually sees in step 1.
 *
 * DRIFT WARNING: if that prompt changes, re-bake instead of editing these strings by
 * hand. Editing here makes the site promise cards the product will not produce.
 *   cd ~/henway/backend && ./.venv/bin/python \
 *     ~/henway-launch-content/site-retrieval-fix/bake-pain-cards.py
 *
 * Baked 2026-07-16 with claude-sonnet-4-6.
 *
 * The eight industries here must stay identical to INDUSTRIES in
 * henway/frontend/src/industries.ts. The app validates the inbound `?industry=`
 * against that list and silently ignores anything it does not recognise, which
 * strands the visitor on the picker we just told them they could skip. Verified
 * matching 2026-08-11 (the app's ninth entry, 'Other', is a UI affordance and is
 * deliberately not deep-linkable).
 */

export type PainCard = { category: string; sentence: string };

export const PAIN_CARDS: { industry: string; cards: PainCard[] }[] = [
  {
    industry: 'Management Consulting',
    cards: [
      { category: 'Workflow', sentence: 'I spend half my week updating slide decks instead of solving client problems.' },
      { category: 'Cost', sentence: 'I lost a big engagement last quarter because our proposal took too long to finish.' },
      { category: 'Tools', sentence: 'My project data lives in Excel, email, and PowerPoint with no single source of truth.' },
      { category: 'Outcomes', sentence: 'I want to show clients clear ROI from our work but struggle to prove the numbers.' },
    ],
  },
  {
    industry: 'Marketing Agency',
    cards: [
      { category: 'Workflow', sentence: 'I spend half my week writing status updates and chasing client approvals by email.' },
      { category: 'Cost', sentence: 'I lose retainer clients because we miss deadlines when the team is stretched too thin.' },
      { category: 'Tools', sentence: 'My project tool, billing software, and ad dashboards never sync, so I fix errors by hand.' },
      { category: 'Outcomes', sentence: 'I want to take on more clients without burning out the team we already have.' },
    ],
  },
  {
    industry: 'HR and People Ops',
    cards: [
      { category: 'Workflow', sentence: 'I spend half my week chasing managers to finish performance reviews on time.' },
      { category: 'Cost', sentence: 'Slow hiring means open roles sit empty and teams miss their quarterly goals.' },
      { category: 'Tools', sentence: 'My ATS, payroll, and onboarding tools don\'t connect, so I enter the same data twice.' },
      { category: 'Outcomes', sentence: 'I want to spot burnout early, but my data never tells me until someone quits.' },
    ],
  },
  {
    industry: 'Learning and Development',
    cards: [
      { category: 'Workflow', sentence: 'I spend most of my week updating slide decks and rewriting the same training content.' },
      { category: 'Cost', sentence: 'I lost a corporate client last month because my course catalog felt outdated and thin.' },
      { category: 'Tools', sentence: 'My LMS, authoring tool, and spreadsheets never sync, so I track completions twice by hand.' },
      { category: 'Outcomes', sentence: 'I want learners to show real skill gains at work, not just pass a quiz.' },
    ],
  },
  {
    industry: 'Healthcare Clinic',
    cards: [
      { category: 'Workflow', sentence: 'I spend hours each week chasing down patient paperwork and insurance approvals manually.' },
      { category: 'Cost', sentence: 'I lose money every month on no-shows because we have no good reminder system.' },
      { category: 'Tools', sentence: 'My scheduling, billing, and patient records software never sync, so staff re-enters data constantly.' },
      { category: 'Outcomes', sentence: 'I wish I could spot high-risk patients early enough to actually prevent costly problems.' },
    ],
  },
  {
    industry: 'Financial Services',
    cards: [
      { category: 'Workflow', sentence: 'I spend hours each week pulling client account data from reports by hand.' },
      { category: 'Cost', sentence: 'I\'ve lost clients who moved their money because I didn\'t follow up in time.' },
      { category: 'Tools', sentence: 'My portfolio, CRM, and compliance tools don\'t sync, so I enter data twice daily.' },
      { category: 'Outcomes', sentence: 'I wish I could spot which clients need a financial review before they call me.' },
    ],
  },
  {
    industry: 'Legal Practice',
    cards: [
      { category: 'Workflow', sentence: 'I spend half my week drafting the same routine contracts and client letters over again.' },
      { category: 'Cost', sentence: 'I\'ve lost clients because slow document turnaround made me look unprepared or unreliable.' },
      { category: 'Tools', sentence: 'My billing software, case notes, and email all live in separate places I can\'t connect.' },
      { category: 'Outcomes', sentence: 'I want to spend more time advising clients and less time chasing paperwork and deadlines.' },
    ],
  },
  {
    industry: 'Real Estate',
    cards: [
      { category: 'Workflow', sentence: 'I spend hours each week scheduling showings and following up with buyers by hand.' },
      { category: 'Cost', sentence: 'I lose deals because slow responses let another agent swoop in and close first.' },
      { category: 'Tools', sentence: 'My MLS, CRM, and email are all separate, so I copy the same data everywhere.' },
      { category: 'Outcomes', sentence: 'I wish I could spend more time with serious buyers and less on paperwork.' },
    ],
  },
];
