/**
 * "Newly possible" spark cards for the idea side of the homepage fork.
 *
 * NOT hand-written marketing copy. Generated by calling the app's own
 * `get_signal(context="", lens="opportunity")` — the same function behind the
 * /signal route — so the site shows what the product actually produces.
 *
 * STALENESS WARNING: these claim to be current. Unlike the pain cards, they rot.
 * Regenerate monthly:
 *   cd ~/henway/backend && ./.venv/bin/python \
 *     ~/henway-launch-content/site-retrieval-fix/refresh-sparks.py
 *
 * Editing these strings by hand makes the site promise cards the product will
 * not produce. Regenerate instead.
 *
 * Generated 2026-08-12 via PREVIEW_MODEL, the model the /signal route passes.
 */

export type Spark = { title: string; why: string };

export const SPARKS_GENERATED = '2026-08-12';

export const SPARKS: Spark[] = [
  { title: "Help customers buy the right size online", why: "Your returns drop when people get the right fit before they order." },
  { title: "Turn your email into a work calendar", why: "You stop double-booking meetings and wasting time finding open slots." },
  { title: "Answer customer questions at night", why: "Your team sleeps while problems get solved and people stay happy." },
  { title: "Make your prices match what each customer pays", why: "You earn more money from the same store without changing how you work." },
];
